var BMapLib=window.BMapLib=BMapLib||{};
(function(){function f(a){this._markerClusterer=a;this._map=a.getMap();this._minClusterSize=a.getMinClusterSize();this._isAverageCenter=a.isAverageCenter();this._center=null;this._markers=[];this._gridBounds=null;this._isReal=!1;this._clusterMarker=new BMapLib.TextIconOverlay(this._center,this._markers.length,{styles:this._markerClusterer.getStyles()})}var k=function(a,b,c){var d=b,e=h(d.getNorthEast().lng,-180,180);b=h(d.getSouthWest().lng,-180,180);var f=h(d.getNorthEast().lat,-74,74),d=h(d.getSouthWest().lat,
-74,74);b=new BMap.Bounds(new BMap.Point(b,d),new BMap.Point(e,f));e=a.pointToPixel(b.getNorthEast());b=a.pointToPixel(b.getSouthWest());e.x+=c;e.y-=c;b.x-=c;b.y+=c;c=a.pixelToPoint(e);a=a.pixelToPoint(b);return new BMap.Bounds(a,c)},h=function(a,b,c){b&&(a=Math.max(a,b));c&&(a=Math.min(a,c));return a},l=function(a,b){var c=-1;if("[object Array]"===Object.prototype.toString.call(b))if(b.indexOf)c=b.indexOf(a);else for(var d=0,e;e=b[d];d++)if(e===a){c=d;break}return c},d=BMapLib.MarkerClusterer=function(a,
b){if(a){this._map=a;this._markers=[];this._clusters=[];a=b||{};this._gridSize=a.gridSize||60;this._maxZoom=a.maxZoom||18;this._minClusterSize=a.minClusterSize||2;this._isAverageCenter=!1;void 0!=a.isAverageCenter&&(this._isAverageCenter=a.isAverageCenter);this._styles=a.styles||[];var c=this;this._map.addEventListener("zoomend",function(){c._redraw()});this._map.addEventListener("moveend",function(){c._redraw()});a=a.markers;"[object Array]"===Object.prototype.toString.call(a)&&this.addMarkers(a)}};
d.prototype.addMarkers=function(a){for(var b=0,c=a.length;b<c;b++)this._pushMarkerTo(a[b]);this._createClusters()};d.prototype._pushMarkerTo=function(a){-1===l(a,this._markers)&&(a.isInCluster=!1,this._markers.push(a))};d.prototype.addMarker=function(a){this._pushMarkerTo(a);this._createClusters()};d.prototype._createClusters=function(){for(var a=this._map.getBounds(),b=k(this._map,a,this._gridSize),a=0,c;c=this._markers[a];a++)!c.isInCluster&&b.containsPoint(c.getPosition())&&this._addToClosestCluster(c);
b=this._markers.length;for(a=0;a<b;a++)this._clusters[a]&&this._clusters[a].render()};d.prototype._addToClosestCluster=function(a){var b=4E6,c=null;a.getPosition();for(var d=0,e;e=this._clusters[d];d++){var g=e.getCenter();g&&(g=this._map.getDistance(g,a.getPosition()),g<b&&(b=g,c=e))}c&&c.isMarkerInClusterBounds(a)?c.addMarker(a):(e=new f(this),e.addMarker(a),this._clusters.push(e))};d.prototype._clearLastClusters=function(){for(var a=0,b;b=this._clusters[a];a++)b.remove();this._clusters=[];this._removeMarkersFromCluster()};
d.prototype._removeMarkersFromCluster=function(){for(var a=0,b;b=this._markers[a];a++)b.isInCluster=!1};d.prototype._removeMarkersFromMap=function(){for(var a=0,b;b=this._markers[a];a++)b.isInCluster=!1,tmplabel=b.getLabel(),this._map.removeOverlay(b),b.setLabel(tmplabel)};d.prototype._removeMarker=function(a){var b=l(a,this._markers);if(-1===b)return!1;tmplabel=a.getLabel();this._map.removeOverlay(a);a.setLabel(tmplabel);this._markers.splice(b,1);return!0};d.prototype.removeMarker=function(a){if(a=
this._removeMarker(a))this._clearLastClusters(),this._createClusters();return a};d.prototype.removeMarkers=function(a){for(var b=!1,c=0;c<a.length;c++)var d=this._removeMarker(a[c]),b=b||d;b&&(this._clearLastClusters(),this._createClusters());return b};d.prototype.clearMarkers=function(){this._clearLastClusters();this._removeMarkersFromMap();this._markers=[]};d.prototype._redraw=function(){this._clearLastClusters();this._createClusters()};d.prototype.getGridSize=function(){return this._gridSize};
d.prototype.setGridSize=function(a){this._gridSize=a;this._redraw()};d.prototype.getMaxZoom=function(){return this._maxZoom};d.prototype.setMaxZoom=function(a){this._maxZoom=a;this._redraw()};d.prototype.getStyles=function(){return this._styles};d.prototype.setStyles=function(a){this._styles=a;this._redraw()};d.prototype.getMinClusterSize=function(){return this._minClusterSize};d.prototype.setMinClusterSize=function(a){this._minClusterSize=a;this._redraw()};d.prototype.isAverageCenter=function(){return this._isAverageCenter};
d.prototype.getMap=function(){return this._map};d.prototype.getMarkers=function(){return this._markers};d.prototype.getClustersCount=function(){for(var a=0,b=0,c;c=this._clusters[b];b++)c.isReal()&&a++;return a};f.prototype.addMarker=function(a){if(this.isMarkerInCluster(a))return!1;if(!this._center)this._center=a.getPosition(),this.updateGridBounds();else if(this._isAverageCenter){var b=this._markers.length+1,c=(this._center.lat*(b-1)+a.getPosition().lat)/b,b=(this._center.lng*(b-1)+a.getPosition().lng)/
b;this._center=new BMap.Point(b,c);this.updateGridBounds()}a.isInCluster=!0;this._markers.push(a)};f.prototype.render=function(){var a=this._markers.length;if(a<this._minClusterSize)for(var b=0;b<a;b++)this._map.addOverlay(this._markers[b]);else this._map.addOverlay(this._clusterMarker),this._isReal=!0,this.updateClusterMarker()};f.prototype.isMarkerInCluster=function(a){if(this._markers.indexOf)return-1!=this._markers.indexOf(a);for(var b=0,c;c=this._markers[b];b++)if(c===a)return!0;return!1};f.prototype.isMarkerInClusterBounds=
function(a){return this._gridBounds.containsPoint(a.getPosition())};f.prototype.isReal=function(a){return this._isReal};f.prototype.updateGridBounds=function(){var a=new BMap.Bounds(this._center,this._center);this._gridBounds=k(this._map,a,this._markerClusterer.getGridSize())};f.prototype.updateClusterMarker=function(){if(this._map.getZoom()>this._markerClusterer.getMaxZoom()){this._clusterMarker&&this._map.removeOverlay(this._clusterMarker);for(var a=0,b;b=this._markers[a];a++)this._map.addOverlay(b)}else if(this._markers.length<
this._minClusterSize)this._clusterMarker.hide();else{this._clusterMarker.setPosition(this._center);this._clusterMarker.setText(this._markers.length);var c=this._map,d=this.getBounds();this._clusterMarker.addEventListener("click",function(a){c.setViewport(d)})}};f.prototype.remove=function(){for(var a=0;this._markers[a];a++)tmplabel=this._markers[a].getLabel(),this._markers[a].getMap()&&this._map.removeOverlay(this._markers[a]),this._markers[a].setLabel(tmplabel);this._map.removeOverlay(this._clusterMarker);
this._markers.length=0;delete this._markers};f.prototype.getBounds=function(){for(var a=new BMap.Bounds(this._center,this._center),b=0,c;c=this._markers[b];b++)a.extend(c.getPosition());return a};f.prototype.getCenter=function(){return this._center}})();