var BMapLib=window.BMapLib=BMapLib||{};
(function(){var l,b=l=b||{version:"1.3.8"};(function(){b.guid="$BAIDU$";window[b.guid]=window[b.guid]||{};b.dom=b.dom||{};b.dom.g=function(a){return"string"==typeof a||a instanceof String?document.getElementById(a):a&&a.nodeName&&(1==a.nodeType||9==a.nodeType)?a:null};b.g=b.G=b.dom.g;b.dom.getDocument=function(a){a=b.dom.g(a);return 9==a.nodeType?a:a.ownerDocument||a.document};b.lang=b.lang||{};b.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};b.isString=b.lang.isString;
b.dom._g=function(a){return b.lang.isString(a)?document.getElementById(a):a};b._g=b.dom._g;b.browser=b.browser||{};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(b.browser.ie=b.ie=document.documentMode||+RegExp.$1);b.dom.getComputedStyle=function(a,d){a=b.dom._g(a);var e=b.dom.getDocument(a);return e.defaultView&&e.defaultView.getComputedStyle&&(a=e.defaultView.getComputedStyle(a,null))?a[d]||a.getPropertyValue(d):""};b.dom._styleFixer=b.dom._styleFixer||{};b.dom._styleFilter=b.dom._styleFilter||[];
b.dom._styleFilter.filter=function(a,d,e){for(var f=0,c=b.dom._styleFilter,g;g=c[f];f++)if(g=g[e])d=g(a,d);return d};b.string=b.string||{};b.string.toCamelCase=function(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})};b.dom.getStyle=function(a,d){var e=b.dom;a=e.g(a);d=b.string.toCamelCase(d);var f=a.style[d]||(a.currentStyle?a.currentStyle[d]:"")||e.getComputedStyle(a,d);if(!f){var c=e._styleFixer[d];c&&(f=c.get?c.get(a):b.dom.getStyle(a,
c))}if(c=e._styleFilter)f=c.filter(d,f,"get");return f};b.getStyle=b.dom.getStyle;/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(b.browser.opera=+RegExp.$1);b.browser.isWebkit=/webkit/i.test(navigator.userAgent);b.browser.isGecko=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);b.browser.isStrict="CSS1Compat"==document.compatMode;b.dom.getPosition=function(a){a=b.dom.g(a);var d=b.dom.getDocument(a),e=b.browser,f=b.dom.getStyle;0<e.isGecko&&d.getBoxObjectFor&&f(a,"position");
var c={left:0,top:0},g;if(a==(e.ie&&!e.isStrict?d.body:d.documentElement))return c;if(a.getBoundingClientRect)a=a.getBoundingClientRect(),c.left=Math.floor(a.left)+Math.max(d.documentElement.scrollLeft,d.body.scrollLeft),c.top=Math.floor(a.top)+Math.max(d.documentElement.scrollTop,d.body.scrollTop),c.left-=d.documentElement.clientLeft,c.top-=d.documentElement.clientTop,a=d.body,d=parseInt(f(a,"borderLeftWidth")),f=parseInt(f(a,"borderTopWidth")),e.ie&&!e.isStrict&&(c.left-=isNaN(d)?2:d,c.top-=isNaN(f)?
2:f);else{g=a;do{c.left+=g.offsetLeft;c.top+=g.offsetTop;if(0<e.isWebkit&&"fixed"==f(g,"position")){c.left+=d.body.scrollLeft;c.top+=d.body.scrollTop;break}g=g.offsetParent}while(g&&g!=a);if(0<e.opera||0<e.isWebkit&&"absolute"==f(a,"position"))c.top-=d.body.offsetTop;for(g=a.offsetParent;g&&g!=d.body;)c.left-=g.scrollLeft,e.opera&&"TR"==g.tagName||(c.top-=g.scrollTop),g=g.offsetParent}return c};b.event=b.event||{};b.event._listeners=b.event._listeners||[];b.event.on=function(a,d,e){d=d.replace(/^on/i,
"");a=b.dom._g(a);var f=function(d){e.call(a,d)},c=b.event._listeners,g=b.event._eventFilter,h=d;d=d.toLowerCase();g&&g[d]&&(f=g[d](a,d,f),h=f.type,f=f.listener);a.addEventListener?a.addEventListener(h,f,!1):a.attachEvent&&a.attachEvent("on"+h,f);c[c.length]=[a,d,e,f,h];return a};b.on=b.event.on;(function(){var a=window[b.guid];b.lang.guid=function(){return"TANGRAM__"+(a._counter++).toString(36)};a._counter=a._counter||1})();window[b.guid]._instances=window[b.guid]._instances||{};b.lang.isFunction=
function(a){return"[object Function]"==Object.prototype.toString.call(a)};b.lang.Class=function(a){this.guid=a||b.lang.guid();window[b.guid]._instances[this.guid]=this};window[b.guid]._instances=window[b.guid]._instances||{};b.lang.Class.prototype.dispose=function(){delete window[b.guid]._instances[this.guid];for(var a in this)b.lang.isFunction(this[a])||delete this[a];this.disposed=!0};b.lang.Class.prototype.toString=function(){return"[object "+(this._className||"Object")+"]"};b.lang.Event=function(a,
d){this.type=a;this.returnValue=!0;this.target=d||null;this.currentTarget=null};b.lang.Class.prototype.addEventListener=function(a,d,e){if(b.lang.isFunction(d)){!this.__listeners&&(this.__listeners={});var f=this.__listeners,c;if("string"==typeof e&&e){if(/[^\w\-]/.test(e))throw"nonstandard key:"+e;c=d.hashCode=e}0!=a.indexOf("on")&&(a="on"+a);"object"!=typeof f[a]&&(f[a]={});c=c||b.lang.guid();d.hashCode=c;f[a][c]=d}};b.lang.Class.prototype.removeEventListener=function(a,d){if("undefined"==typeof d||
(!b.lang.isFunction(d)||(d=d.hashCode))&&b.lang.isString(d)){!this.__listeners&&(this.__listeners={});0!=a.indexOf("on")&&(a="on"+a);var e=this.__listeners;if(e[a])if("undefined"!=typeof d)e[a][d]&&delete e[a][d];else for(var f in e[a])delete e[a][f]}};b.lang.Class.prototype.dispatchEvent=function(a,d){b.lang.isString(a)&&(a=new b.lang.Event(a));!this.__listeners&&(this.__listeners={});d=d||{};for(var e in d)a[e]=d[e];var f=this.__listeners,c=a.type;a.target=a.target||this;a.currentTarget=this;0!=
c.indexOf("on")&&(c="on"+c);b.lang.isFunction(this[c])&&this[c].apply(this,arguments);if("object"==typeof f[c])for(e in f[c])f[c][e].apply(this,arguments);return a.returnValue};b.lang.inherits=function(a,d,b){var e,c,g=a.prototype;c=new Function;c.prototype=d.prototype;c=a.prototype=new c;for(e in g)c[e]=g[e];a.prototype.constructor=a;a.superClass=d.prototype;"string"==typeof b&&(c._className=b)};b.inherits=b.lang.inherits})();var k=BMapLib.TextIconOverlay=function(a,d,b){this._position=a;this._text=
d;this._options=b||{};this._styles=this._options.styles||[];!this._styles.length&&this._setupDefaultStyles()};l.lang.inherits(k,BMap.Overlay,"TextIconOverlay");k.prototype._setupDefaultStyles=function(){for(var a=[53,56,66,78,90],b=0,e;e=a[b];b++)this._styles.push({url:"http://api.map.baidu.com/library/TextIconOverlay/1.2/src/images/m"+b+".png",size:new BMap.Size(e,e)})};k.prototype.initialize=function(a){this._map=a;this._domElement=document.createElement("div");this._updateCss();this._updateText();
this._updatePosition();this._bind();this._map.getPanes().markerMouseTarget.appendChild(this._domElement);return this._domElement};k.prototype.draw=function(){this._map&&this._updatePosition()};k.prototype.getText=function(){return this._text};k.prototype.setText=function(a){!a||this._text&&this._text.toString()==a.toString()||(this._text=a,this._updateText(),this._updateCss(),this._updatePosition())};k.prototype.getPosition=function(){return this._position};k.prototype.setPosition=function(a){!a||
this._position&&this._position.equals(a)||(this._position=a,this._updatePosition())};k.prototype.getStyleByText=function(a,b){a=parseInt(a);a=parseInt(a/10);a=Math.max(0,a);a=Math.min(a,b.length-1);return b[a]};k.prototype._updateCss=function(){var a=this.getStyleByText(this._text,this._styles);this._domElement.style.cssText=this._buildCssText(a)};k.prototype._updateText=function(){this._domElement&&(this._domElement.innerHTML=this._text)};k.prototype._updatePosition=function(){if(this._domElement&&
this._position){var a=this._domElement.style,b=this._map.pointToOverlayPixel(this._position);b.x-=Math.ceil(parseInt(a.width)/2);b.y-=Math.ceil(parseInt(a.height)/2);a.left=b.x+"px";a.top=b.y+"px"}};k.prototype._buildCssText=function(a){var b=a.url,e=a.size,f=a.anchor,c=a.offset,g=a.textColor||"black";a=a.textSize||10;var h=[];7>l.browser.ie?h.push('filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="'+b+'");'):(h.push("background-image:url("+b+");"),b="0 0",c instanceof
BMap.Size&&(b=c.width+"px "+c.height+"px"),h.push("background-position:"+b+";"));e instanceof BMap.Size&&(f instanceof BMap.Size?(0<f.height&&f.height<e.height&&h.push("height:"+(e.height-f.height)+"px; padding-top:"+f.height+"px;"),0<f.width&&f.width<e.width&&h.push("width:"+(e.width-f.width)+"px; padding-left:"+f.width+"px;")):(h.push("height:"+e.height+"px; line-height:"+e.height+"px;"),h.push("width:"+e.width+"px; text-align:center;")));h.push("cursor:pointer; color:"+g+"; position:absolute; font-size:"+
a+"px; font-family:Arial,sans-serif; font-weight:bold");return h.join("")};k.prototype._bind=function(){function a(a,b){var c=a.srcElement||a.target,d=a.clientX||a.pageX,f=a.clientY||a.pageY;a&&b&&d&&f&&c&&(a=l.dom.getPosition(e.getContainer()),b.pixel=new BMap.Pixel(d-a.left,f-a.top),b.point=e.pixelToPoint(b.pixel));return b}if(this._domElement){var b=this,e=this._map,f=l.lang.Event;l.event.on(this._domElement,"mouseover",function(c){b.dispatchEvent(a(c,new f("onmouseover")))});l.event.on(this._domElement,
"mouseout",function(c){b.dispatchEvent(a(c,new f("onmouseout")))});l.event.on(this._domElement,"click",function(c){b.dispatchEvent(a(c,new f("onclick")))});l.event.on(this._domElement,"touchend",function(c){b.dispatchEvent(a(c,new f("onclick")))})}}})();